name: Build-Push-Deploy

on:
  workflow_call:
    inputs:
      IMAGE_NAME:          { required: true,  type: string }
      DOCKERFILE_PATH:     { required: false, type: string, default: ./Dockerfile }
      MANIFEST_PATH:       { required: true,  type: string }
      KUBE_NAMESPACE:      { required: false, type: string,  default: default }
      EXTRA_BUILD_ARGS:    { required: false, type: string }
    secrets:
      HARBOR_URL:       { required: true }
      HARBOR_USERNAME:  { required: true }
      HARBOR_PASSWORD:  { required: true }
      KUBE_CONFIG:      { required: true }

jobs:
  build-push-deploy:
    runs-on: self-hosted
    env:
      REGISTRY: ${{ secrets.HARBOR_URL }}
      IMAGE:    ${{ inputs.IMAGE_NAME }}
      TAG:      ${{ github.sha }}
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file:   ${{ inputs.DOCKERFILE_PATH }}
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
          ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
        build-args: |
          ${{ inputs.EXTRA_BUILD_ARGS }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with: { version: v1.29.4 }

    - name: Write kubeconfig
      run: echo "${KUBE_CONFIG}" | base64 -d > $HOME/.kube/config
      env: { KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }} }

    - name: Image tag substitution
      run: |
        sed -i "s|IMAGE_PLACEHOLDER|${REGISTRY}/${IMAGE}:${TAG}|g" "${{ inputs.MANIFEST_PATH }}"

    - name: Apply manifest
      run: kubectl apply -n "${{ inputs.KUBE_NAMESPACE }}" -f "${{ inputs.MANIFEST_PATH }}"

    - name: Wait for rollout
      run: |
        kubectl rollout status deploy $(yq '.metadata.name' "${{ inputs.MANIFEST_PATH }}") \
          -n "${{ inputs.KUBE_NAMESPACE }}" --timeout=120s
